# Generated by Django 6.0.7 on 2026-07-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, choices=[('HK', 'Hong Kong'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('SG', 'Singapore'), ('TW', 'Taiwan'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('NL', 'Netherlands'), ('AE', 'UAE'), ('IN', 'India')], default='HK', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='partnership',
            field=models.CharField(blank=True, choices=[('skyforce', 'Skyforce'), ('others', 'Others')], default='skyforce', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
