# Generated by Django 6.0.7 on 2026-07-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_city_client_country_client_fax_client_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
