# Generated by Django 6.0.7 on 2026-07-23 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='databaseconnection',
            options={'ordering': ['name'], 'verbose_name': 'Database Connection', 'verbose_name_plural': 'Database Connections'},
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='building',
            name='area_unit',
            field=models.CharField(choices=[('m2', 'm²'), ('ft2', 'ft²')], default='ft2', max_length=5),
        ),
        migrations.AddField(
            model_name='building',
            name='base_temp_cooling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='base_temp_heating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='building_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('retail', 'Retail'), ('hotel', 'Hotel'), ('residential', 'Residential'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use'), ('data_centre', 'Data Centre'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='country',
            field=models.CharField(choices=[('HK', 'Hong Kong'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('SG', 'Singapore'), ('TW', 'Taiwan'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('FR', 'France'), ('NL', 'Netherlands'), ('AE', 'UAE'), ('IN', 'India')], default='HK', max_length=3),
        ),
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='currency',
            field=models.CharField(choices=[('HKD', 'HKD – Hong Kong Dollar'), ('USD', 'USD – US Dollar'), ('CNY', 'CNY – Chinese Yuan'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('SGD', 'SGD – Singapore Dollar'), ('JPY', 'JPY – Japanese Yen')], default='HKD', max_length=5),
        ),
        migrations.AddField(
            model_name='building',
            name='dashboard_chart',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='building',
            name='db_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='core.databaseconnection'),
        ),
        migrations.AddField(
            model_name='building',
            name='energy_star_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='building',
            name='gross_floor_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/photos/'),
        ),
        migrations.AddField(
            model_name='building',
            name='postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='tech_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='building',
            name='tech_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='tech_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='timezone',
            field=models.CharField(choices=[('Asia/Hong_Kong', 'Asia/Hong Kong (UTC+8)'), ('Asia/Shanghai', 'Asia/Shanghai (UTC+8)'), ('Asia/Singapore', 'Asia/Singapore (UTC+8)'), ('Asia/Tokyo', 'Asia/Tokyo (UTC+9)'), ('Europe/London', 'Europe/London (UTC+0/+1)'), ('America/New_York', 'America/New_York (UTC-5/-4)'), ('Australia/Sydney', 'Australia/Sydney (UTC+10/+11)')], default='Asia/Hong_Kong', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='building',
            name='weather_unit_group',
            field=models.CharField(choices=[('metric', 'Metric (°C)'), ('imperial', 'Imperial (°F)')], default='metric', max_length=12),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='core.client'),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='database',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='engine',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'MS SQL Server'), ('sqlite', 'SQLite')], default='postgres', max_length=20),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='options',
            field=models.TextField(blank=True, help_text='Extra connection params (JSON)'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.PositiveIntegerField(default=5432),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='username',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='BuildingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Database name')),
                ('db_file', models.FileField(upload_to='building_databases/', verbose_name='Database file')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building Database (db_test)',
                'verbose_name_plural': 'Building Databases (db_test)',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='building_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='core.buildingdatabase', verbose_name='Uploaded DB (db_test)'),
        ),
    ]
