# Generated by Django 6.0.7 on 2026-07-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_building_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='db_connection',
        ),
        migrations.DeleteModel(
            name='DatabaseConnection',
        ),
    ]
