# Generated by Django 6.0.7 on 2026-07-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_building_db_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgroup',
            name='can_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='read_buildings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='read_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='read_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='read_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='read_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='read_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='write_buildings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='write_clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='write_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='write_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='write_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='write_users',
            field=models.BooleanField(default=False),
        ),
    ]
