# Generated by Django 6.0.7 on 2026-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientgroup_can_read_clientgroup_can_write_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinguser',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='daily_delivery',
            field=models.CharField(default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='daily_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='receive_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='single_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='timezone',
            field=models.CharField(choices=[('Asia/Hong_Kong', 'Asia/Hong Kong (UTC+8)'), ('Asia/Shanghai', 'Asia/Shanghai (UTC+8)'), ('Asia/Singapore', 'Asia/Singapore (UTC+8)'), ('Asia/Tokyo', 'Asia/Tokyo (UTC+9)'), ('Europe/London', 'Europe/London (UTC+0/+1)'), ('America/New_York', 'America/New_York (UTC-5/-4)'), ('Australia/Sydney', 'Australia/Sydney (UTC+10/+11)')], default='Asia/Hong_Kong', max_length=50),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='view_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildinguser',
            name='work_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
