# Generated by Django 6.0.7 on 2026-07-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_buildinguser_cell_phone_buildinguser_daily_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingdatabase',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Building Database', 'verbose_name_plural': 'Building Databases'},
        ),
    ]
